version: '3'

services:
  # Auth App
  auth-api:
    container_name: thepro-auth-api
    build:
      context: .
      dockerfile: ./apps/auth-api/Dockerfile
    command: node ./index.js
    extends:
      file: docker-compose.base.yaml
      service: nx-app-base
    ports:
      - 7801:8801 # API Entry port

  # Resource App
  resource-api:
    container_name: thepro-resource-api
    build:
      context: .
      dockerfile: ./apps/resource-api/Dockerfile
    extends:
      file: docker-compose.base.yaml
      service: nx-app-base
    command: node ./index.js
    ports:
      - 7802:8802 # API Entry port
